# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "David Kennedy"
description: > # this means to ignore newlines until "email:"
   Engineer. InfoSec Geek. Extroverted introvert.

email: djknndy@gmail.com
#blog logo
logo: "/assets/images/dk_logo.png"
# blog cover
cover: "/assets/images/colourful-silicon-wafer.jpg"

name: 'David Kennedy'
author: 'David Kennedy'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://djkenne.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@mrbigkens'

#fill in disqus shortname to use disqus
disqus: djkenne

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/mrbigkens
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/djkenne
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
